site_name: Nexor
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_root_full_path: false
            parameter_headings: false
            show_object_full_path: false
            show_root_toc: false
            show_symbol_type_toc: true
            type_parameter_headings: false
nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Modules:
      - API: modules/api.md
      - Configuration: modules/config.md
      - Health: modules/health.md
      - Infrastructure: modules/infrastructure.md
      - Logging: modules/logging.md
      - Observability: modules/observability.md
      - Utilities: modules/utils.md
